app:
  name: 'soundproof-backend-demo'
  version: '1.0.0'

http:
  port: ':8080'

logger:
  log_level: 'debug'
  rollbar_env: 'soundproof-backend-demo'

postgres:
  url: 'postgresql://postgres:password@localhost:5432/postgres'
  pool_max: 2